@host = localhost

@port = 3000

@apiVersion = v1.0

@schema = meal-db

@query_string = burger

GET http://{{host}}:{{port}}/api/{{apiVersion}}/{{schema}}/search/{{{{query_string}}}}


POST http://{{host}}:{{port}}/api/{{apiVersion}}/
Content-Type: application/json

{
    "": ""
}